version: '3.9'
services:
  postgres:
    container_name: postgres
    build:
      context: ../
      dockerfile: Dockerfile.postgres.dev
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  backend:
    container_name: backend
    depends_on:
      - postgres
    volumes:
      - ../src:/var/www/html/
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ../
      dockerfile: Dockerfile.backend
    ports:
      - 3000:80

volumes:
  postgres: